services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: siamp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-siampDb}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - siamp-network

  # NestJS Application
  nestjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: siamp-nestjs
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/${MONGO_DATABASE:-siampDb}?authSource=admin
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT:-3000}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - siamp-network
    command: npm run start:dev

  # MongoDB Admin Interface (Optional)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: siamp-mongo-express
    restart: unless-stopped
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - siamp-network

volumes:
  mongodb_data:
    driver: local

networks:
  siamp-network:
    driver: bridge