services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: siamp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-siampDb}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - siamp-network
  # NestJS Application
  nestjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: siamp-nestjs
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/${MONGO_DATABASE:-siampDb}?authSource=admin
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT:-3000}
      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      # MQTT Configuration
      - MQTT_URL=${MQTT_URL:-mqtt://mosquitto:1883}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME:-siamp_server}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-mqtt_secure_pass}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID:-siamp_backend}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - mosquitto
    networks:
      - siamp-network
    command: npm run start:dev
  # MongoDB Admin Interface (Optional)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: siamp-mongo-express
    restart: unless-stopped
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - siamp-network  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: siamp-mosquitto
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"      # MQTT port
      - "${MQTT_WS_PORT:-9001}:9001"   # WebSocket port
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-siamp_server}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-mqtt_secure_pass}
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/init-mosquitto.sh:/mosquitto/init-mosquitto.sh
    networks:
      - siamp-network
    command: sh -c "dos2unix /mosquitto/init-mosquitto.sh 2>/dev/null || true; sh /mosquitto/init-mosquitto.sh"

volumes:
  mongodb_data:
    driver: local

networks:
  siamp-network:
    driver: bridge