services:  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: siamp-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - siamp-network  # NestJS Application
  nestjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    container_name: siamp-nestjs-prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}
      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      # MQTT Configuration
      - MQTT_URL=${MQTT_URL}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
    depends_on:
      - mongodb
      - mosquitto
    networks:
      - siamp-network
      
  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: siamp-mosquitto-prod
    restart: always
    ports:
      - "${MQTT_PORT}:1883"      # MQTT port
      - "${MQTT_WS_PORT}:9001"   # WebSocket port
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
      - MQTT_URL=${MQTT_URL:-mqtt://mosquitto:1883}
      - MQTT_WS_PORT=${MQTT_WS_PORT:-9001}
    volumes:
      - /DATA/AppData/Jenkins/var/jenkins_home/workspace/SIAMP-G/mosquitto/config:/mosquitto/config
      - /DATA/AppData/Jenkins/var/jenkins_home/workspace/SIAMP-G/mosquitto/data:/mosquitto/data
      - /DATA/AppData/Jenkins/var/jenkins_home/workspace/SIAMP-G/mosquitto/log:/mosquitto/log
      - /DATA/AppData/Jenkins/var/jenkins_home/workspace/SIAMP-G/mosquitto/init-mosquitto.sh:/init-mosquitto.sh:ro
    networks:
      - siamp-network
    # Usando ruta absoluta al script
    command: sh /init-mosquitto.sh

volumes:
  mongodb_data:
    driver: local

networks:
  siamp-network:
    driver: bridge
